version: '2'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: vessel/app
    ports:
     - "${APP_PORT}:80"
    environment:
      CONTAINER_ENV: "${APP_ENV}"
      XDEBUG_HOST: "${XDEBUG_HOST}"
      WWWUSER: "${WWWUSER}"
    volumes:
     - .:/var/www/html
    networks:
     - vessel
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
      args:
        uid: "${WWWUSER}"
    image: vessel/node
    user: node
    volumes:
     - .:/var/www/html
    networks:
     - vessel
  postgres:
    image: mdillon/postgis
    environment:
      POSTGRES_DB: appforward
      POSTGRES_USER: homestead
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    volumes:
     - postgres-data:/var/lib/postgresql/data
 # We cannot mount local directory directly as docker on windows give permission issues.
 # More info https://forums.docker.com/t/data-directory-var-lib-postgresql-data-pgdata-has-wrong-ownership/17963/24
    ports:
     - "5432:5432"
    networks:
     - vessel
    restart: unless-stopped
  redis:
    image: redis:alpine
    volumes:
      - vesselredis:/data
    networks:
      - vessel
networks:
  vessel:
    driver: "bridge"
volumes:
  postgres-data:
    driver: "local"
  vesselredis:
    driver: "local"
